apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
        - name: data-ingestion-container
          image: 376163012258.dkr.ecr.us-east-1.amazonaws.com/data-ingestion-app:latest
          ports:
            - containerPort : 8080


---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
spec:
  selector:
    app: data-ingestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

